### ISSUE TITLE
Add support for Jedis and Lettuce

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [bucket4j/bucket4j#254]
In the scope of #36 was added Redis support on top of Reddison java client. It seems that supporting yet another two clients should not be hard.

**Comment by ttulka** [comment]
Hey, would it be acceptable for you regarding the project concept to add support for spring-data-redis, too? 

If so, I can create a PR soon.

**Comment by vladimir-bukhtoyarov** [comment]
Has been released with version 7.6.0 https://bucket4j.com/7.6.0/toc.html#bucket4j-redis
