### ISSUE TITLE
TTL support for DynamoDB backend

### ISSUE THREAD

**Issue by Avinm** [bucket4j/bucket4j#265]
I noticed that the redis implementation has an option to add TTL and dynamo one does not.
Was this ever considered?
Could try raising a PR if there's nothing blocking the implementation.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @Avinm 

If dynamoDb has TTL feature, there are nothing that prevents to add TTL to DynamoDb integration. Feel free to prepare pull request if you have a time to do this.

**Comment by Avinm** [comment]
Yes, DynamoDB does have a TTL feature: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html 
However, items are not immediately deleted. Therefore it is upon the implementation to filter out older items that are pending deletion.
Do you have any recommendation on how to decide the TTL window? I'm thinking that ideally the TTL window is computed by bucket4j as the largest time window among all rate limiting rules, but it looks like the redis implementation takes in the TTL parameter as input?

**Comment by vladimir-bukhtoyarov** [comment]
Currently, I recommend to choose TTL by following criteria:
1. TTL should be >= max proposed time window among all rate limiting rules.
2. Also if capacity > refill_tokens, it is possible where [classic bandwidth](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/Bandwidth.java#L116) is used, then TTL choosed at previous step should be multiplied by X, where X = capacity/refill_tokens.

However, I want to notice that current support of TTL for redis is awkward and choosing right TTL is hard, and even impossible sometimes. There is better implementation of TTL in the [CaffeineProxyManager](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-caffeine/src/main/java/io/github/bucket4j/caffeine/CaffeineProxyManager.java#L49) that does not require to provide initial estimates, instead it relies on the [time that required to full refilling of consumed tokens](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-caffeine/src/main/java/io/github/bucket4j/caffeine/CaffeineProxyManager.java#L62), **keepAfterRefillDuration** is not critical can be zero.

Please wait for Monday, I will add this concept to the **AbstractCompareAndSwapBasedProxyManager** and you will be able to write the code similar that written in CaffeineProxyManager.

**Comment by vladimir-bukhtoyarov** [comment]
@Avinm the branch **7.6** is the right branch to start your pull request. **RedissonBasedProxyManager** has been modified in this branch, use it as example of flexible TTL calculation.

**Comment by augustlakia** [comment]
Is this issue still relevant? @Avinm are you working on this ?

**Comment by vladimir-bukhtoyarov** [comment]
Hello @augustlakia 

The issue is actual. It should be easy exercise, but I have not time currently to accomplish it, so you are welcome to provide pull-request.

**Comment by Avinm** [comment]
@augustlakia
Unfortunately I haven't yet gotten around to starting on this. This is because I realized that I would currently only be using this on finite cardinality keys.
Feel free to raise a PR if you want to pick it up, if not, I'll give a heads up here a couple of days before I start

**Comment by vladimir-bukhtoyarov** [comment]
Declined
