### ISSUE TITLE
Invalid Hazelcast documentation for 7.x & 8.x docs

### ISSUE THREAD

**Issue by abelsromero** [bucket4j/bucket4j#285]
I am working on an upgrade from v6 and I found the docs are not valid.
They state the `BucketConfiguration` `build` method requires 2 params, but it has 0.

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/5781153/182563052-deea51c7-ba6e-4eba-a6f4-b85824fa7f82.png">

The key is not passes to the `BucketConfiguration` builder but to the `Bucket` builder.

**Comment by abelsromero** [comment]
If it's ok, this is an easy fix, I can work on the current asciidoctor branch alongside other minnor doc fixes.

**Comment by vladimir-bukhtoyarov** [comment]
Yes, it is bug, right example should be as you described above.

**Comment by vladimir-bukhtoyarov** [comment]
documentation has been fixed for 7.6.0 and 8.0.1
