### ISSUE TITLE
tag missing problem 

### ISSUE THREAD

**Issue by CChengjie** [bucket4j/bucket4j#301]
I'm doing a research on tags .
We found that versions like 6.0.1、6.0.2 was released in Maven, but there was no corresponding tag in github, Can you help me with this?
1）What is the reason for tag's absence?

- a、This version code has problems, such as the loophole, compatibility and interface issues, etc.
- b、This version has functional problems, such as unreasonable function planning, basic function cannot be used
- c、Forgot to tag
- d、Don't care or is too trouble
- e、This version does not need to be tagged.
- f、others，_

2） To solve this problem, we propose a method that can find the true commit of version to help developers quickly locate the problem code and fix the bug. Here are the possible true commits given by our method. Can you confirm whether or not the actual commits are included, and if not, which ones?
**6.0.1**
['04c64b4baa91afc80a7117af573bd86080807f99', '09a62a91510a20e505e564e0d212119acf848e17', '9dd2d9c66e02e678c8a9e596492f5502e3be1eca', 'd0afc8880f74736ac85c4c17f589eb8e05fc50b4']
**6.0.2**
['048432d509fa52c1f81705edda19acc14e83eb57', 'd3260ed548b8d6e8851ddadd448d82a4625db047']

♥ This question is very important to our research. Thank you for your time!

**Comment by vladimir-bukhtoyarov** [comment]
Hello @CChengjie 

It was long time ago, I do not remember the reasons.
