### ISSUE TITLE
add a TTL for the cache item

### ISSUE THREAD

**Issue by yangw14** [bucket4j/bucket4j#305]
Is it possible to add a configuration item in the bucket4j configuration
to set the TTL of the rate limit cache item?

If validation by username and the bucket have no TTL,
a lot of records will be left in the cache.

Thanks in advance.

**Comment by vladimir-bukhtoyarov** [comment]
What cache technology do you use?

**Comment by yangw14** [comment]
Sorry for the lateness, I use Redis as the cache solution.

**Comment by vladimir-bukhtoyarov** [comment]
> Sorry for the lateness, I use Redis as the cache solution.

It is strange. I do not remember the times when TTL for Redis was not supported in Bucket4j. Do you use Bucket4j directly or through some integration(like bucket4j-spring-boot-starter)?

**Comment by yangw14** [comment]
yes, I use the bucket4j-spring-boot-starter, and use redisson to connect the Redis server.

**Comment by vladimir-bukhtoyarov** [comment]
In such case, please adress your question directly to the [https://github.com/MarcGiffing/bucket4j-spring-boot-starter](bucket4j-spring-boot-starter) repository
