### ISSUE TITLE
Support for Elasticache Redis Cluster enabled 

### ISSUE THREAD

**Issue by lindahm** [bucket4j/bucket4j#306]
Hi,

By any chance, is there any plan to support , e.g: [Lettuce Redis cluster client](https://github.com/lettuce-io/lettuce-core/blob/6.2.0.RELEASE/src/test/java/io/lettuce/examples/ConnectToRedisCluster.java)?
Looking at the current API [LettuceBasedProxyManager](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-redis/src/main/java/io/github/bucket4j/redis/lettuce/cas/LettuceBasedProxyManager.java) only take a non clustered Redis client.

Thank you!

**Comment by vladimir-bukhtoyarov** [comment]
Hello @lindahm 

Feel free to prepare pull-request with desired functionality.

**Comment by smtylmzx** [comment]
Hi, lettuce cluster supported, this pr https://github.com/bucket4j/bucket4j/pull/338 🙂
