### ISSUE TITLE
isAsyncModeSupported false for AbstractSelectForUpdateBasedProxyManager

### ISSUE THREAD

**Issue by amin2718** [bucket4j/bucket4j#308]
Hello,

I notice that `AbstractSelectForUpdateBasedProxyManager.isAsyncModeSupported` returns false for `MySQLSelectForUpdateBasedProxyManager`. Am I missing something? Does this mean that I cannot consume tokens asynchronously if I'm using MySQL as the persistent bucket store?

**Comment by vladimir-bukhtoyarov** [comment]
Hello @amin2718 

Async mode is not supported for MySQL because JDBC does not provide asynchronous functionality.

**Comment by amin2718** [comment]
Thanks for the explanation. One thing I noticed about the API is that `tryConsume` returns a boolean, whereas `consumeIgnoringRateLimits` returns an additional piece of information, which is the amount of rate limit violation.

If `tryConsume` did the same thing: return a 0 if consumption was successful, and > 0 to describe the amount of violation that would have occurred, it would be quite useful for building a distributed rate limiter where high accuracy is not needed. The reason is because we can store the nanoseconds locally and automatically deny requests for a period without making any remote request.

There are many cases where the tradeoff is quite acceptable. Is such a thing possible with the current API?

**Comment by vladimir-bukhtoyarov** [comment]
There is "tryConsumeAndReturnRemaining" for such cases. This method return [ConsumptionProbe](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/ConsumptionProbe.java) object that in case of reject provides time in nanos which need to wait until requested amount of tokens will be refilled via [getNanosToWaitForRefill](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/ConsumptionProbe.java#L154) method.

**Comment by amin2718** [comment]
Thank you, I hadn't seen that. Thank you for your time and help.
