### ISSUE TITLE
Allow proxy managers to find bucket by key before attempting to build

### ISSUE THREAD

**Issue by shanqyeet** [bucket4j/bucket4j#309]
Hi, 

In the current approach of creating new bucket or getting an existing bucket from cache, any proxy manager that we used must go through the following steps

1. Create the bucket configuration
2. retrieve existing or create new bucket through the builder, i.e. `proxyManager.builder.build(bucketKey, bucketConfiguration)`

In my case, we are using the hazelcast connector and based on our requirements, we need to access DB to pull user specific bucket configuration details (only required when its first time creating bucket) even when we know the bucket exists.

Hence, that got me thinking if there is anyway we can first check if the bucket exists in the cache through some method like `getBucketByKey()` that perhaps would throw a `BucketNotFoundException` and then lead us to create a new bucket through the builder method. This way, we can bypass the need to pull configuration data or any computation to create the bucket configuration   when the bucket configuration is actually not required in the case of retrieving an existing bucket.

Would love to hear more from fellow users and contributors on this and the suitability/possibility to have `getBucketByKey` before attempting to create.

Thank you.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @shanqyeet 

Please describe why [build(K key, Supplier<BucketConfiguration> configurationSupplier)](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/distributed/proxy/RemoteBucketBuilder.java#L95) is not helpful.
