### ISSUE TITLE
Simple rate limiter

### ISSUE THREAD

**Issue by tbee** [bucket4j/bucket4j#320]
I'm probably simply not getting something, but I use an API that accepts at most 10 requests per minute, so I need to throttle my client. From Bucket4j's documentation I get that this should be simple. 
https://bucket4j.com/8.1.1/toc.html#using-bucket-as-throttler

```
Bandwidth bandwidth = Bandwidth.simple(10, Duration.ofMinutes(1));
Bucket bucket = Bucket.builder().addLimit(bandwidth).build();
```

However, if I run an endless loop with:
```
bucket.asBlocking().consumeUninterruptibly(1);
```

The first 10 tokens being distributed immediately, then for the 11th token there is a short 2 second pause, but he 11th token  is handed out only 6 seconds after the 1st was. This alone would make for 11 requests within the first minute and would immediately break the throttle restriction. It should wait for at least a minute before handing out the 11th token. (The 12th and further tokens are also handed out too soon.)

I can hack around this by using intervallyAligned, but this behavior seems so totally wrong.

How do I setup a bucket that hands out available tokens immediately, but then correctly waits the full minute for each token before refilling?

**Comment by vladimir-bukhtoyarov** [comment]
Hello @tbee 

> This alone would make for 11 requests within the first minute and would immediately break the throttle restriction. It should wait for at least a minute before handing out the 11th token.

Definitelly no. Bucket4j is implementation of token-bucket algorithm. Token-bucket by itself is not addressed to solve restrictions like _**N permits/ M time_window**_.  Its math model is more complicated, I higly recommend to read something about it, especially abourt **burst**.

 > I can hack around this by using intervallyAligned, but this behavior seems so totally wrong.

Both **intervally** and **intervallyAligned** refills are not helpfull to prevent the burst, because the burst is inherent part of token bucket.

**Comment by tbee** [comment]
Then the documentation which states "100 times per 1 minute" is confusing. To me at least, because that is exactly the behavior I am looking for. And in my example I get more that 100 times in the first minute.

Anyhow, I've implemented a RateLimiter backed by a DelayQueue, and that works as I need it to. So thanks for responding!

**Comment by vladimir-bukhtoyarov** [comment]
> nyhow, I've implemented a RateLimiter backed by a DelayQueue, and that works as I need it to. So thanks for responding!

The sorted hash map where timestamp is the key, is the place where  typical programmer starts usually. This honey-moon can prolong as long as capacity does not become too huge(like terabytes per second) as well as amount of buckets does not increase like millions buckets per application. The typical way in which programmers give up to satisfy hard limit N/M is described there https://www.blogger.com/blog/post/edit/3564973286727861628/5966188154863706900

Most discussions have stopped 30 years ago, when Token-Bucket was accepted as preferred algorithm for network devices, as a algorithm that can operated on fixed(and small) amount of memory.

**Comment by tbee** [comment]
The advantage of using DelayQueue is that the whole waiting is handled for you. One has to insert Delayed implementations with the correct timestamp when they may execute.

And what can I say? The service I'm addressing limits the request in the way I described; max 10 per 1 minute, in its most simple and unsmoothed form.
