### ISSUE TITLE
Bucket4j expecting redis to be up and running, if redis goes down my application going down

### ISSUE THREAD

**Issue by surendrab6** [bucket4j/bucket4j#339]
Hi Team,

Iam trying bucket4j with redis in distributed environment. Iam using LettuceBasedProxyManager to connect to redis to get/store buckets in redis. My application is expecting redis to be up and running while starting application, also when redis goes down when application is running, my application going down. In my case i want to use redis as optional. If redis is down, my application should work fine with out rate limit. Can you please confirm is there any way to do this ?

**Comment by vladimir-bukhtoyarov** [comment]
There is nothing special to Bucket4j. Firstly read [this checklist](https://bucket4j.com/8.1.1/toc.html#distributed-checklist) and decide what is behavior that need to be applied when Redis is down. Secondly, apply any open-sourced circuit-breaker what you want, or write own.

**Comment by vladimir-bukhtoyarov** [comment]
According to Redis availability on application start:
Distributed buckets are lazy, proxies do not try to communicate with remote storage until proxy is explicitly called by user, so unawailabily Redis on start should not affect application startup.
