### ISSUE TITLE
Exception occurred when tried to read configuration from Redis

### ISSUE THREAD

**Issue by Spector96** [bucket4j/bucket4j#344]
Hi team.

We have a distributed system on Azure, and I tried to get a configuration for a bucket, but I got java.lang.IllegalStateException: java.io.EOFException. 

We are using jdk zulu17 (17.0.3-1).
We are using LettuceBasedProxyManager to maintain the buckets. 

Here is the relevant trace: 
java.lang.IllegalStateException: java.io.EOFException\n\tat io.github.bucket4j.distributed.serialization.InternalSerializationHelper.deserializeState(InternalSerializationHelper.java:53)\n\tat io.github.bucket4j.distributed.proxy.generic.GenericEntry.<init>(GenericEntry.java:40)\n\tat io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager.execute(AbstractCompareAndSwapBasedProxyManager.java:72)\n\tat io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager.execute(AbstractCompareAndSwapBasedProxyManager.java:51)\n\tat io.github.bucket4j.distributed.proxy.AbstractProxyManager.getProxyConfiguration(AbstractProxyManager.java:93)\n\tat 

[error.txt](https://github.com/bucket4j/bucket4j/files/10546195/error.txt)
 
Here is the code snippet: 

        proxyManager = LettuceBasedProxyManager.builderFor(RedisClient.create(redisURI))
                .withExpirationStrategy(ExpirationAfterWriteStrategy.none())
                .build();

        for (var entry : buckets.entrySet()) {
            Optional<BucketConfiguration> bucketConfiguration = proxyManager
                    .getProxyConfiguration(entry.getKey().getBytes());
            Bucket bucket;
            if (bucketConfiguration.isPresent()) {
                bucket = proxyManager.builder().build(entry.getKey().getBytes(), bucketConfiguration.get());
            } else {
                bucket = createNewBucket(entry);
            }
            bucketStates.put(entry.getKey(), bucket);
        }

The key is: cHNtZ2KxczpDZlRuZHGHTjQzZHFnQ0FBQm1ZTg==

As I checked, it works with other keys, but with this one, it throws the exception. Is there a restriction for the key what characters can it contain? 

Thanks,
Peter

**Comment by vladimir-bukhtoyarov** [comment]
Hello @Spector96 

To investigate deserialization issu I need for:
* byte array that is stored by key _cHNtZ2KxczpDZlRuZHGHTjQzZHFnQ0FBQm1ZTg==_
* Bucket4j version that is used.

Also be sure that another pieces of your(or another) application does store something else with this key.

**Comment by Spector96** [comment]
Hello @vladimir-bukhtoyarov 

Thank you for the quick response. 

The array is: [99, 72, 78, 116, 90, 50, 82, 120, 99, 122, 112, 68, 90, 108, 82, 117, 90, 72, 108, 80, 86, 106, 81, 122, 90, 72, 70, 110, 81, 48, 70, 66, 81, 109, 49, 90, 84, 103, 61, 61]
Bucket4j version: 7.6.0

Thanks for the advice, we have more test environments that will connect the same Redis cache, so I plan to add the environment name as a prefix to the key.

**Comment by Spector96** [comment]
Hello @vladimir-bukhtoyarov

You are right, there was an already existing key in the Redis that was not created by Bucket4j. 
The value was a "5", so the byte array was only that: [53]. 

Thanks for the advice, we have more test environments that will connect the same Redis cache, so I plan to add the environment name as a prefix to the key.

Sorry for the inconvenience, you can close the issue.
