### ISSUE TITLE
PostgreSQLadvisoryLockBasedProxyManager can only use Long keys

### ISSUE THREAD

**Issue by std46** [bucket4j/bucket4j#353]
```PostgreSQLadvisoryLockBasedProxyManager``` extends  ```AbstractLockBasedProxyManager<Long>``` which prevents me from using a String based key.

Converting my String keys to Long keys through hashing would not be feasible as I am working with a few million buckets. Using Long to String references would need an entire separate db lookup to find the Long keys mapped back to the String keys.

Would it be possible to generify ```PostgreSQLadvisoryLockBasedProxyManager```? My other option is to just copy the class and update it to fit my use case.

Thanks

**Comment by vladimir-bukhtoyarov** [comment]
Hello @std46 

This issue duplicates https://github.com/bucket4j/bucket4j/issues/351

I am going to release it in the end of the month.

**Comment by std46** [comment]
Thanks @vladimir-bukhtoyarov . Sorry for the duplicate issue.

**Comment by vladimir-bukhtoyarov** [comment]
Released with version 8.2.0
