### ISSUE TITLE
How can I figure out that bucket capacity is full for a certain user and then use this over capacity to somewhere else.

### ISSUE THREAD

**Issue by adityapareek16** [bucket4j/bucket4j#354]
Hi,

I have to create an application where each user is assigned some static limits. So, some user might be under utilizing these limits and some might be getting throttled. When bucket is getting full then those tokens wouldn't be added to the bucket and will be ignored. So, instead of throwing them out can we give these tokens to other user who is frequently getting throttled so that downstream systems are better utilized?

Thanks in advance.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @adityapareek16,

These requirements can not be achived with Bucket4j, because there are no any process that refills tokens in backround, so nobody can detect underutilization and do something with underutilized tokens.

**Comment by adityapareek16** [comment]
Hi @vladimir-bukhtoyarov ,

Thank you so much for the quick reply.

`because there are no any process that refills tokens in backround `===> I know you are the best person who is aware of it but just for my understanding, I could see that the method `Refill.greedy(....) ` fills the token at constant rate so that these tokens can be utilized by the consumer. So, is it not correct ?

`so nobody can detect underutilization`. ====> When bucket capacity is full and then new token wouldn't be added to the bucket and would be ignored. So, is there any way to determine it ?

Thanks,

**Comment by vladimir-bukhtoyarov** [comment]
Closed as imppossible to implement without huge redesign.
