### ISSUE TITLE
How to implement custom proxy manager for Bucket4j to integrate with homegrown cache?

### ISSUE THREAD

**Issue by deshpandeanoop** [bucket4j/bucket4j#357]
As of today, bucket4j support provides integration with cache solutions like Hazelcast, Redis etc., we have a requirement where we wanted to use bucket4j with our homegrown cache solution. Are there any steps documented that helps us with implementing the custom integration?

**Comment by vladimir-bukhtoyarov** [comment]
Hello @deshpandeanoop 

To build custom integration you need to answer to following question: does your solution support any variant of RPC when on JVM may call another JVM? It can be something like EntryProccessors from JCache, VoltDb's stored procedures, or serializable functions in Infinispan. If your solution supports RPC, just extend AbstractProxyManager and implement abstract methods, use IgniteProxyManager or InfinispanProxyManager for reference. Do not forget to think about transaction isolation, you need to clearly understand how to protect data from concurrent modifications.

If RPC is not supported then you need to choose one of basic class for extending:
* `SelectForUpdateBasedProxyManager` if your solution supports the selecting and locking the data via one remote call.
* `AbstractLockBasedProxyManager` if your soulution supports the locks on the data.
* `AbstractCompareAndSwapBasedProxyManager` if your solution supports CAS.
* If nothing from above is supported then anyway you can use `AbstractLockBasedProxyManager` by delegating the locking acquiring to another solutions like Redis or something similar.
* If your sulution supports the both CAS and locking, then choose apropriate way based on proposed contention on the buckets - usually locking win when contention is high and vise versa.

Then you need to test resulting code via via extending [this test-base](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/test/java/io/github/bucket4j/tck/AbstractDistributedBucketTest.java). TCK is available in maven central with special type **test-jar**
```xml
        <dependency>
            <groupId>com.bucket4j</groupId>
            <artifactId>bucket4j-core</artifactId>
            <version>${bucket4j.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>
```
AbstractDistributedBucketTest contains multiple checks for many aspects of distributed bucket implementation. Do not skip this step, it is ultimately major, see thos thread https://github.com/bucket4j/bucket4j/discussions/349#discussioncomment-4912745
