### ISSUE TITLE
Bucket interface is not serializable

### ISSUE THREAD

**Issue by kabilanvk** [bucket4j/bucket4j#359]
Can we make the io.github.bucket4j.Bucket serializable?  Since it's not serializable couldn't store it externally.

**Comment by kabilanvk** [comment]
Thanks. It would be helpful if you include a serialization example in your documentation about storing buckets in httpsession.
https://bucket4j.com/8.2.0/toc.html#limiting-the-rate-of-access-to-rest-api

This will give a picture to users who externalize sessions.

**Comment by vladimir-bukhtoyarov** [comment]
This utility can help:

```
import io.github.bucket4j.local.LocalBucket;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

public class SerializableBucketContainer implements Externalizable {

    private LocalBucket bucket;

    public LocalBucket getBucket() {
        return bucket;
    }

    public void setBucket(LocalBucket bucket) {
        this.bucket = bucket;
    }

    @Override
    public void writeExternal(ObjectOutput out) throws IOException {
        byte[] snapshot = bucket.toBinarySnapshot();
        out.write(snapshot);
    }

    @Override
    public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
        byte[] snapshot = (byte[]) in.readObject();
        bucket = LocalBucket.fromBinarySnapshot(snapshot);
    }

}
```
Store it inside session instead of bucket.

**Comment by vladimir-bukhtoyarov** [comment]
@kabilanvk

Distributed buckets API was changed a lot in scope of release 7.0.0 https://bucket4j.com/7.0.0/release-notes.html
Package `io.github.bucket4j.grid` does not exist anymore. See actual documentation fore Coherence there https://bucket4j.com/8.2.0/toc.html#bucket4j-coherence

Also, I want to notice that buckets that are instantiated by CoherenceProxyManager can not be serialized to byte array via SerializableBucketContainer mentioneed above, becuase these buckets do not implement LocalBucket interface. It is better to avoid storing such buckets in session, instead store the ID, and bucket params like capacity, refill period, and create bucket each time when you need to check limit, see https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/distributed/proxy/RemoteAsyncBucketBuilder.java#L87
