### ISSUE TITLE
How to capture the over-flown token events when using bucket4J with HazelCast integration?

### ISSUE THREAD

**Issue by deshpandeanoop** [bucket4j/bucket4j#365]
We use the bucket4j library along with the HazelCast integration & have a use-case to tap onto the overflown tokens. To elaborate the term _over flown token_, we are referring it when the algorithm attempts to fill a token in a bucket that contains tokens to its defined capacity. Upon exploration, we found there exists listeners in the hazelcast library `EntryUpdatedListener`, `EntryAddedListener` etc, to hook-in the custom logic whenever a token is added or consumed. However, I don't see these listeners getting invoked when a over flow scenario occurs. Is there any listener in place that we can use to tap into the over flow event?

We use the `bucket4j-hazelcast` version `4.10.0`

**Comment by vladimir-bukhtoyarov** [comment]
Hello @deshpandeanoop 

There is no way to capture such events.

**Comment by deshpandeanoop** [comment]
Thanks @vladimir-bukhtoyarov for the confirmation
