### ISSUE TITLE
Support for Hazelcast 5

### ISSUE THREAD

**Issue by KaYBlitZ** [bucket4j/bucket4j#369]
Hi, I was reading the documentation: https://bucket4j.com/8.2.0/toc.html . I am adding this issue to keep track of adding support for Hazelcast 5 which seems to have been released 2 years ago: https://mvnrepository.com/artifact/com.hazelcast/hazelcast

**Comment by vladimir-bukhtoyarov** [comment]
5.+.+ is supported without exceptions.
