### ISSUE TITLE
Bucket4J for OracleSql

### ISSUE THREAD

**Issue by mesarvagya** [bucket4j/bucket4j#372]
Hello,

I was looking to see if Bucket4J supports Oracle SQL. I do see it supports Oracle Coherence, but not DB.

Is there any plan to add OracleDB support similar to PostgreSQL?

**Comment by vladimir-bukhtoyarov** [comment]
@mesarvagya hello,

I have tried to create something working with Oracle, it looks good for me and passes all test. Try to use OracleSelectForUpdateBasedProxyManager from this commit https://github.com/bucket4j/bucket4j/commit/9dd27e84a0e0f4a7e3f14ee15265e82c89ab8a84
See OracleSelectForUpdateLockBasedTransactionTest from this commit for debug and clarifications.

It is not planned to release something until Jule 2023, so just copy and past this implementation to your project.

**Comment by mesarvagya** [comment]
Thanks @vladimir-bukhtoyarov . I will give this a try and update the thread.

**Comment by mesarvagya** [comment]
Hi @vladimir-bukhtoyarov 
I was able to run the code you shared for Oracle DB. I added a small comment on https://github.com/bucket4j/bucket4j/commit/9dd27e84a0e0f4a7e3f14ee15265e82c89ab8a84

I have another question. Since the implementation is using `SELECT FOR UPDATE`, what would be the behavior for multiple consumers taking tokens for same bucket e.g. When 1 consumer is trying to get a token, will other consumers wait for first to release its row lock?

Is there a way in bucket4J where multiple consumers for same bucket can get tokens independently?

Thanks very much.

**Comment by mesarvagya** [comment]
Thanks @vladimir-bukhtoyarov for the feedback.

Please let me know the comments on https://github.com/bucket4j/bucket4j/commit/9dd27e84a0e0f4a7e3f14ee15265e82c89ab8a84 makes sense or not.

Closing this since you already have a change in place.

**Comment by vladimir-bukhtoyarov** [comment]
released with version 8.4.0
