### ISSUE TITLE
Update Junit from Junit 4 to Junit 5

### ISSUE THREAD

**Issue by namhptran** [bucket4j/bucket4j#375]
Hi @vladimir-bukhtoyarov, I've got a few changes I'd like to contribute and would like to use new features from Junit 5 in order to better organise tests. This repository is still using Junit 4 which was last updated 2 years ago, so would we be able to start considering migrating the test suite to the latest Junit 5.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @namhptran 

I have no objections to upgrade Junit, but have no time to do this. So feel free to prepare pull request.

**Comment by salmansharifov** [comment]
Hi @vladimir-bukhtoyarov , @namhptran .  I can upgrade junit version, if it is ok.

**Comment by namhptran** [comment]
Thanks @salmansharifov I've had a quick go but it seems to break some of the tests for me 
https://github.com/namhptran/bucket4j/actions/runs/4973035423/jobs/8898617127?pr=2
Would be good if someone else could have a look!

**Comment by salmansharifov** [comment]
@namhptran It seems that surefire requires a specific provider for jupiter. Adding dependency to surefire plugin could solve it.
```
<dependencies>
    <dependency>
         <groupId>org.junit.platform</groupId>
         <artifactId>junit-platform-surefire-provider</artifactId>
          <version>1.1.0</version>
    </dependency>
</dependencies>
```

**Comment by namhptran** [comment]
That sounds about right, https://stackoverflow.com/questions/36970384/surefire-is-not-picking-up-junit-5-tests

I will give it another go today

**Comment by namhptran** [comment]
Initial Junit uplift PR as https://github.com/bucket4j/bucket4j/pull/377

**Comment by vladimir-bukhtoyarov** [comment]
Fixed by https://github.com/bucket4j/bucket4j/pull/377
