### ISSUE TITLE
Clojure based Bucket4J implemented for Datomic database

### ISSUE THREAD

**Issue by fr33m0nk** [bucket4j/bucket4j#380]
Hi,

First of all many thanks for such a wonderful library.
[Datomic Database](https://www.datomic.com/) is fairly popular Database in Clojure community
I have implemented Bucket4J support for Datomic Database using `AbstractCompareAndSwapBasedProxyManager` and was wondering if it is worth adding to project's ReadMe.
This is the [link to library](https://github.com/fr33m0nk/clj-bucket4j-datomic).

Thanks again for all the hard work 🙂 .

**Comment by vladimir-bukhtoyarov** [comment]
Hello @fr33m0nk 

I will add link to your project there https://bucket4j.com/#third-party-integrations

**Comment by vladimir-bukhtoyarov** [comment]
Link has been added
