### ISSUE TITLE
Migrate void returning async methods to `CompletableFuture<?>`

### ISSUE THREAD

**Issue by chrisdennis** [bucket4j/bucket4j#386]
Since the callers of the async equivalents of void returning methods do not by definition care about the returned value, these returns can be easily migrated to `CompletableFuture<?>`. This allows implementations of these methods to directly return a `CompletableFuture` bearing an arbitrary type without needing to remap it.

**Comment by chrisdennis** [comment]
This is the first in sequence of issues discovered implementing a new backend for bucket4j at Software AG. The are all centered around various tweaks to the async API to allow for a smoother (and hopefully more performant) integration with backends . If you'd rather a more holistic discussion of the full set of changes on a dev mailing list please let me know.

**Comment by vladimir-bukhtoyarov** [comment]
> If you'd rather a more holistic discussion of the full set of changes on a dev mailing list please let me know.

Yes, it is interesting to look at whole list of awkwards.

**Comment by vladimir-bukhtoyarov** [comment]
Declined.
