### ISSUE TITLE
Version 7.0.0 onwards HazelcastProxyManager does not provide getProxy method

### ISSUE THREAD

**Issue by KaeYan93** [bucket4j/bucket4j#399]
Hi, 

From my understanding, the hazelcast is used to store the bucket with a key, and when it comes to rate limiting, the application needs to get the bucket from hazelcast to check if there is still token left in bucket.

As of version 6.4.0, the HazelcastProxyManager still provides getProxy to get Bucket, but it is not supported after. Can I first verify my understanding, and if it's correct, how does the application now retrieves the bucket with the newer version? In your docs, I cannot see any steps to retrieve a bucket, only build bucket code is available. 

Thanks.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @KaeYan93 

This method was removed in order to prevent eniffecient usage of API like:
```java
Bucket bucket = proxyManager.getProxy("42");
if (bucket.tryConsume(1)) {
   ...
}
```
There are two network requests in the scenario above, It is not optimal usage of API.

New API does not allow to act in this way.

**Comment by KaeYan93** [comment]
Thanks for prompt reply. Understand the concern of inefficient calls for old APIs. 

With the new approach below you mentioned, is there a way that i can retrieve the same bucket for the same key when i need to consume it, without having to keep track that it has been consumed? Because the code (Builder) seems will create the new bucket for the same key everytime. 
```
BucketConfiguration configuration = BucketConfiguration.builder()
                .addLimit(Bandwidth.simple(1_000, Duration.ofMinutes(1)))
                .addLimit(Bandwidth.simple(200, Duration.ofSeconds(10)))
                .build();

Bucket bucket = proxyManager.builder().build(key, configuration);
```

**Comment by vladimir-bukhtoyarov** [comment]
If bucket was created before, it will not be rewritten, so multiple client will operate with same bucket.

**Comment by KaeYan93** [comment]
If the bucket is persisted before and there is a configuration change, i will need to removeProxy and build a new one with the same code above?

**Comment by KaeYan93** [comment]
Also, just curious, if the bucket was created before and if the next client retrieve the same bucket (with same key) with the builder method, wouldnt it that it will get the bucket from cache and that it might have the similar inefficient network calls as well?

**Comment by vladimir-bukhtoyarov** [comment]
> If the bucket is persisted before and there is a configuration change, i will need to removeProxy and build a new one with the same code above?

It not needs to remove bucket in such case. There is special API [On-the-fly configuration replacement](https://bucket4j.com/8.3.0/toc.html#configuration-replacement)

**Comment by vladimir-bukhtoyarov** [comment]
> Also, just curious, if the bucket was created before and if the next client retrieve the same bucket (with same key) with the builder method, wouldnt it that it will get the bucket from cache and that it might have the similar inefficient network calls as well?

Default Bucket4j integration with Hazelcast is implemented on the top of [EntryProcessor functionality](https://hazelcast.com/blog/an-easy-performance-improvement-with-entryprocessor/). There is no regular get->modify-write ->commit pattern that we usually use in our typical enterprise code.

**Comment by KaeYan93** [comment]
Hi @vladimir-bukhtoyarov, thank you for your response, my above queries is answered already. 

I have 2 more questions:
1. Is there a default refill config if refill config is not specified?
2. For the bucket4j distributed feature, the specific feature is that bucket4j is able to store the bucket information in the distributed cache right? Apart from this, what other features i can leverage?

**Comment by vladimir-bukhtoyarov** [comment]
1. Refill config is always defined. When Bandwidth#simple method is called, it creates Refill behind the scene https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/Bandwidth.java#L105

2. The stable list of features is documented there https://bucket4j.com/8.3.0/toc.html  Threre is interesting package [io.github.bucket4j.distributed.proxy.optimization](https://github.com/bucket4j/bucket4j/tree/master/bucket4j-core/src/main/java/io/github/bucket4j/distributed/proxy/optimization) that is not documented and is not finalized.

**Comment by KaeYan93** [comment]
> If bucket was created before, it will not be rewritten, so multiple clients will operate with same bucket. Provided configuration will be used if and only if it detected that bucket was not persisted yet.

I am using 8.3.0, and i realized that the bucket will be overwritten with new configuration with the code below, after created a bucket. When the bucket was first created, it is also using the method below. Does it mean that when i create the bucket using code below, it is not persisted in the hazelcast yet?

```
BucketConfiguration configuration = BucketConfiguration.builder()
                .addLimit(Bandwidth.simple(1_000, Duration.ofMinutes(1)))
                .addLimit(Bandwidth.simple(200, Duration.ofSeconds(10)))
                .build();

Bucket bucket = proxyManager.builder().build(key, configuration);
```

**Comment by KaeYan93** [comment]
Also, @vladimir-bukhtoyarov my feedback is that it is not intuitive/costly for the user to create the BucketConfiguration again, when retrieving the bucket to do rate limit. My use case is that i will have > 1 application running, and they sharing a hazelcast cluster. If it happen that I need to store my BucketConfiguration so that i can generate the Bucket everytime for rate limit purpose, it would be costly + not intuitive because when i first create bucket, i have already given a key and a bucket configuration to create the bucket. 

The analogy would be e.g. using a HashMap, first i store a key and value pair, subsequently, if i want to get the value from a key, i have to generate the value first to get the key value pair, instead of using the key. 

Please let me know if there is a misunderstanding of the use of APIs. Thanks.

**Comment by vladimir-bukhtoyarov** [comment]
@KaeYan93 

You are right while your cluster is stable. But... What will you do when by any reason bucket had been lost? Without configuration provider the bucket can not be recreated, while current API ressurects bucket for you automatically. 

Comaprision with HashMap is not well suitable there. HashMap is not distributed object, so it would be right to compare HashMap with LocalBucket. LocalBucket is free from described awkwards.

Also, if configuration is costly to create you can use lazy configuration provider:
```java
// lazyConfigurationSupplier is called if and only if bucket is absent in Hazelcast
Supplier<BucketConfiguration> lazyConfigurationSupplier = () -> readFromSlowDatabase(userId);
Bucket bucket = proxyManager.builder().build(userId, lazyConfigurationSupplier)
```

In consclusion:
Current API design is addressed to prevent as many pitfalls related to distributed computations as it possible. Previuos API design did not prevent prefomans and availability problems.

**Comment by vladimir-bukhtoyarov** [comment]
> > If bucket was created before, it will not be rewritten, so multiple clients will operate with same bucket. Provided configuration will be used if and only if it detected that bucket was not persisted yet.
> 
> I am using 8.3.0, and i realized that the bucket will be overwritten with new configuration with the code below, after created a bucket. When the bucket was first created, it is also using the method below. Does it mean that when i create the bucket using code below, it is not persisted in the hazelcast yet?
> 
> ```
> BucketConfiguration configuration = BucketConfiguration.builder()
>                 .addLimit(Bandwidth.simple(1_000, Duration.ofMinutes(1)))
>                 .addLimit(Bandwidth.simple(200, Duration.ofSeconds(10)))
>                 .build();
> 
> Bucket bucket = proxyManager.builder().build(key, configuration);
> ```

It can not be true, otherwise it should be a cause of thouthands reported issues in the bugtracker. This functionality is covered of massive tests suite, and can not be broken in so cheap way.  Try to run this code https://github.com/bucket4j/bucket4j/commit/b3d8788dc3a2bd2c1b5de68b4d0d878633a71357 I have created it to specially demonstrate that problem does not exist.
