### ISSUE TITLE
Redis proxy does not scale

### ISSUE THREAD

**Issue by vtlkvl** [bucket4j/bucket4j#404]
Redis proxy uses CAS to update bucket data and when there is ~400 concurrent requests, CAS starts to fail with a lot of race conditions and failed CAS operations are retried until they all succeed. As we don't want rate limiting to add much latency to user requests, we set a timer for bucket4j calls and when we get 400+ requests that map to the same bucket, they start to fail with timeouts after 3 seconds. With thousands of concurrent requests bucket4j calls may take tens of seconds or even more that leads to the conclusion that current implementation of Redis proxy can't be used for high load systems.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @vtlkvl 

Described problem is not specific for Redis. Numbers can be better for another backends such as Hazelcast but not serriouslly, there are no persistence solutions that can survive until thouthands of transactions per second on the same key.  

There is some usefull package that has not been documented yet https://github.com/bucket4j/bucket4j/tree/master/bucket4j-core/src/main/java/io/github/bucket4j/distributed/proxy/optimization It is especially designed for to solve problem related to high transaction rate on the same key. Examples that shows ability how to use optimizations can be found there https://github.com/bucket4j/bucket4j/tree/8.4/bucket4j-examples/src/test/java/example/distributed/optimizers
Just batching should be enough for start. All examples are written for Hazelcast, but same style can be reused for Redis.

**Comment by vtlkvl** [comment]
Hi @vladimir-bukhtoyarov, thanks for the prompt answer. Thousands of requests from the same origin is not really a big number and many systems should be able to handle it and we are trying to find a proper solution.

Nice idea on batching. I haven't looked at the implementation in detail, but I have an assumption that it works well with a high and consistent request rate, however if requests are intermittent, it will process the batch not when it gets full, but on scheduled time, and it may add to overall user request latency.

I had another idea that requires to partition buckets. Instead of creating one bucket, we could create several buckets that split the capacity and refill rate evenly. When requests comes in, we will use these buckets in a round-robin fashion and we will have to adjust remaining limit if we need to return it to the client. It does not solve the original problem, but it just delays it.

**Comment by vladimir-bukhtoyarov** [comment]
> but I have an assumption that it works well with a high and consistent request rate, however if requests are intermittent, it will process the batch not when it gets full, but on scheduled time, and it may add to overall user request latency.

No. Next batch is being executed imediattely after previous is executed. There is no background scheduling.

> I had another idea that requires to partition buckets. Instead of creating one bucket, we could create several buckets that split the capacity and refill rate evenly. When requests comes in, we will use these buckets in a round-robin fashion and we will have to adjust remaining limit if we need to return it to the client. It does not solve the original problem, but it just delays it.

This hack can be implemented on the client side without bringing it to the library level. In general, I do not think that it is good idea, for some small capacities it would not work at all. Batching significantly reduces the request rate bacause read state only once, applies a bunch of commands one by one to the state in the memory and then saves state only once(if it was 100 commands in the batch then 99 network reqeusts were preserved), while splitting the bucket just reduces contention only, without reducing requeast rate.

It can be only one bad scenario for batching - many client nodes, for hundreds of client nodes CAS will not work well. But it is not hard work to fix. Just introduce microservice with 2-3 nodes and delegate request limiting to this service, this microservice will act as concentrator that reduces contention and request rate.

**Comment by vtlkvl** [comment]
Thanks @vladimir-bukhtoyarov, batching optimization solved the problem. The only thing I'd like to call out is that optimizations work at the `io.github.bucket4j.Bucket` instance level and it would be nice to provide a caching version of `RemoteBucketBuilder` so that users do not need to build caching themselves.

**Comment by vladimir-bukhtoyarov** [comment]
> it would be nice to provide a caching version of RemoteBucketBuilder so that users do not need to build caching themselves.

I will add this option in next release.

**Comment by vladimir-bukhtoyarov** [comment]
> Initially I thought that pending Redis queries would be combined into a single Redis transaction

It is not nessarry to combine something into transaction because there is nothing to combine. Because independently from size of batch we perform one read and one write.

> but really they are executed serially

Exactly, data is read to the app memory from Redis, then bunch of command are applied serially to this data, then data is stored to Redis.
