### ISSUE TITLE
How many concurrent QPS support for Redis based storage

### ISSUE THREAD

**Issue by helloworlde** [bucket4j/bucket4j#407]
Hi, I'm try to use bucket4j as our distributed cluster rate limiter, and I used redis as storage with lettuce. But I found when limit capacity more than 10000 and qps is 11000, there cost lots of time in CAS modify redis data, It's slow down service response time.

The time spend in stack like this(this collected by [arthas#trace](https://arthas.aliyun.com/en/doc/trace.html#trace)), CAS executed 45 times.

```java
`---ts=2023-09-25 13:55:04;thread_name=pool-18-thread-26;id=a2;is_daemon=false;priority=5;TCCL=org.springframework.boot.loader.LaunchedURLClassLoader@51efea79
    `---[45.192243ms] io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager:execute()
        +---[0.01% 0.006011ms ] io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager:beginCompareAndSwapOperation() #49
        `---[99.73% min=0.804747ms,max=1.833075ms,total=45.069022ms,count=45] io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager:execute() #51
            `---[99.36% min=0.799679ms,max=1.825029ms,total=44.778888ms,count=45] io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager:execute()
                +---[0.08% min=5.82E-4ms,max=0.001132ms,total=0.033819ms,count=45] io.github.bucket4j.distributed.remote.Request:getCommand() #70
                +---[47.24% min=0.354223ms,max=1.073221ms,total=21.153375ms,count=45] io.github.bucket4j.distributed.proxy.generic.compare_and_swap.CompareAndSwapOperation:getStateData() #71
                +---[0.11% min=5.21E-4ms,max=0.019406ms,total=0.048751ms,count=45] java.util.Optional:orElse() #71
                +---[0.09% min=6.41E-4ms,max=0.001553ms,total=0.038093ms,count=45] io.github.bucket4j.distributed.remote.Request:getBackwardCompatibilityVersion() #72
                +---[0.36% min=0.001903ms,max=0.02131ms,total=0.162619ms,count=45] io.github.bucket4j.distributed.proxy.generic.GenericEntry:<init>() #72
                +---[0.16% min=8.41E-4ms,max=0.019727ms,total=0.070302ms,count=45] io.github.bucket4j.distributed.proxy.generic.compare_and_swap.AbstractCompareAndSwapBasedProxyManager:getClientSideTime() #73
                +---[1.57% min=0.011341ms,max=0.077655ms,total=0.703968ms,count=45] io.github.bucket4j.distributed.remote.RemoteCommand:execute() #73
                +---[0.06% min=5.0E-4ms,max=8.92E-4ms,total=0.028364ms,count=45] io.github.bucket4j.distributed.proxy.generic.GenericEntry:isModified() #74
                +---[0.25% min=0.001603ms,max=0.006142ms,total=0.112193ms,count=45] io.github.bucket4j.distributed.proxy.generic.GenericEntry:getModifiedStateBytes() #78
                +---[0.07% min=6.11E-4ms,max=9.12E-4ms,total=0.031006ms,count=45] io.github.bucket4j.distributed.proxy.generic.GenericEntry:getModifiedState() #79
                `---[48.52% min=0.395672ms,max=1.251815ms,total=21.72614ms,count=45] io.github.bucket4j.distributed.proxy.generic.compare_and_swap.CompareAndSwapOperation:compareAndSwap() #79
```

- I create Bucket like this:

```java
String resourceKey = "DISTRIBUTED_RATE_LIMIT:" + name;
RedisURI redisUri = RedisURI.builder()
        .withHost("redis-online")
        .withPort(6379)
        .build();

RedisClient client = RedisClient.create(redisUri);
RedisAsyncCommands<byte[], byte[]> command = client.connect(RedisCodec.of(ByteArrayCodec.INSTANCE, ByteArrayCodec.INSTANCE)).async();

Long capacity = 10000L;

Refill refill = Refill.greedy(capacity, Duration.ofSeconds(1));

Bandwidth bandwidth = Bandwidth.classic(capacity, refill)
        .withInitialTokens(capacity);

BucketConfiguration configuration = BucketConfiguration.builder()
        .addLimit(bandwidth)
        .build();

//ClientSideConfig clientSideConfig = ClientSideConfig.getDefault()
//        .withExecutionStrategy(ExecutionStrategy.backgroundTimeBounded(executor, scheduledExecutorService, Duration.ofMillis(5)));

LettuceBasedProxyManager<String> proxyManager = LettuceBasedProxyManager.builderFor(command) 
        .withKeyMapper(Mapper.STRING) 
        .withExpirationStrategy(ExpirationAfterWriteStrategy.basedOnTimeForRefillingBucketUpToMax(Duration.ofSeconds(60)))
        //  .withClientSideConfig(clientSideConfig)
        .build();

AsyncBucketProxy bucket = proxyManager.asAsync().builder()
        .withImplicitConfigurationReplacement(config.getVersion(), TokensInheritanceStrategy.AS_IS)
        .build(resourceKey, configuration);
```

And usage is :

```java
CompletableFuture<ConsumptionProbe> future = bucket.tryConsumeAndReturnRemaining(1);
ConsumptionProbe probe = future.get(config.getTimeout().getNano(), TimeUnit.NANOSECONDS);
Boolean result = probe.isConsumed();
```

And I tried Bucket/AsyncBucketProxy and `ExecutionStrategy.backgroundTimeBounded` in async thread, there has same issue.

I read part of source code, there has two step, first is get the key from redis, and then use eval to modify the data, but in others project like SpringCloud Gateway: [request_rate_limiter.lua](https://github.com/spring-cloud/spring-cloud-gateway/blob/main/spring-cloud-gateway-server/src/main/resources/META-INF/scripts/request_rate_limiter.lua), there has only on Lua script to do this,  so bucket4j need CAS to update, it works well in local application, but in distributed scenes, it works not as expected.

Did I used bucket4j correect? How could I improve performance for this? 
Sorry for my pool English, maybe some description is not precise. Thank you very much.

**Comment by vladimir-bukhtoyarov** [comment]
Hello @helloworlde 

You correctly use the Bucket4j. But for buckets with high contention you need to activate small setting, see this https://github.com/bucket4j/bucket4j/issues/404#issuecomment-1717426333

When creating bucket you need to apply optimization(at list batching)
```java
AsyncBucketProxy bucket = proxyManager.asAsync().builder()
        .withImplicitConfigurationReplacement(config.getVersion(), TokensInheritanceStrategy.AS_IS)
        .withOptimization(Optimizations.batching())
        .build(resourceKey, configuration);
```
Usually, it is enough for middle-size clusters. If contention is still huge then follow to advance in the end of this post https://github.com/bucket4j/bucket4j/issues/404#issuecomment-1718944749

**Comment by helloworlde** [comment]
Hi @vladimir-bukhtoyarov , Thank you for your response.

I had tried to use `withOptimization(Optimizations.batching())` today, and the performance is still not as expected. There has lots of timeout request since I set timeout as 10ms.

I tried to use Lua script as rate limiter, it could support more than 20k QPS in one 2C10G instance.

So may I ask why not use a Lua script as rate limiter in Bucket4J?

**Comment by helloworlde** [comment]
Hi @vladimir-bukhtoyarov, Sorry for the long time no reply, I took a week off.

I created `AsyncBucketProxy` like this.

```java
LettuceBasedProxyManager<String> proxyManager = LettuceBasedProxyManager.builderFor(redisClient) 
        .withKeyMapper(Mapper.STRING) 
        .withExpirationStrategy(ExpirationAfterWriteStrategy.basedOnTimeForRefillingBucketUpToMax(Duration.ofSeconds(60)))
        .build();

AsyncBucketProxy bucket = proxyManager.asAsync().builder()
        .withImplicitConfigurationReplacement(config.getVersion(), TokensInheritanceStrategy.AS_IS)
        .withOptimization(Optimizations.batching())
        .build(resourceKey, configuration);
```

And I had only one `AsyncBucketProxy`  object for test, did I used in right way? Thanks.

**Comment by vladimir-bukhtoyarov** [comment]
Yes it is right code. How many nodes were used in the test? Also what is the stat produced by optimization listener?

**Comment by helloworlde** [comment]
I used a Redis cluster with 10 instances, but the key was hashed to same instance every time, so it is same as only one node. 
The Redis instance in k8s used 2 CPU and 20G memory. It could support 20k QPS with Lua script and the CPU is 100% for single key.

The optimization listener produced that 99% was merged when QPS is 1000. And 100% merged when QPS is 2000, but almost half of request is timeout. And the skip is always zero.

**Comment by vladimir-bukhtoyarov** [comment]
> I used a Redis cluster with 10 instances, but the key was hashed to same instance every time, so it is same as only one node.

It is clear, that only one Redis node is woring in this scenario, I have asked about client nods count. How many client nodes were involved in the test? When client node is node where bucket is instantiated.

> The optimization listener produced that 99% was merged when QPS is 1000. And 100% merged when QPS is 2000, but almost half of request is timeout.

Merged count looks good, skip count is always zero in batching optimization. It looks that amount of concurrent nodes is big enough to make CAS is inefficient. 

Potencially, choosing different style of optimization could help to reduce amount of requests to Redis(you should observe non-zero value of skiiped requests in the listener, it mean amount of requests that was server locally without synchronization with Redis).
```
         long maxUnsynchronizedTokens = some_numbers_of_tokens_that_can_be_consumed_locally_without_synchronization_with_redis;
        Duration maxUnsynchronizedTokens = some_duration_that_you_agree_to_postpone_synchronization_with_redis;
        DelayParameters posponedSynchronization = new DelayParameters(maxUnsynchronizedTokens, maxUnsynchronizedTokens);

        AsyncBucketProxy bucket = proxyManager.asAsync().builder()
            .withImplicitConfigurationReplacement(config.getVersion(), TokensInheritanceStrategy.AS_IS)
            .withOptimization(Optimizations.delaying(posponedSynchronization).withListener(listener))
            .build(resourceKey, configuration);
```

> It could support 20k QPS with Lua script and the CPU is 100% for single key.

This number is similar that another solution provides, like Ignite, Hazelcast, Infinispan. Integrations for JVM based memory storages is built on the top of EntryProcessors that from architecture point of view work the similar as Lua script for Redis. 
I see several alternatives:
* If you agree to lose some accurracy, try to use ```delaying``` optimization, it will reduce amount of requests to the Redis.
* If it is possible use JVM in memory storage - Ignite, Hazelcast or Infinispan.
* Introduce some microservice with 2 nodes, and deligate rate limiting to them, it will reduce concurrency.
* If nothing above is acceptable, and if you do not need of rich functionallity provided by Bucket4j, then use some handwritten lua script.

[Migration bucket4j-redis to Lua scripts](https://github.com/bucket4j/bucket4j/issues/410) will not be done fast, because of huge functionality that need be reimplemented in Lua, so you should not wait for completness of this issue, I do not excpect that I will hav time ti implement it before summer 2024.

**Comment by helloworlde** [comment]
> It is clear, that only one Redis node is woring in this scenario, I have asked about client nods count. How many client nodes were involved in the test? When client node is node where bucket is instantiated.

I have 20 client node for test, but actually, our production envrionment service instance is more than this amount. So CAS operation will not reduce on production envrionment. 

I will have a try for `Optimizations.delaying`, and I think it could work for some scene for me.

After communicate with team, we decided to use Lua script for high QPS distributed scene and use Bucket4j to other distributed scene and local scence because of we need rich functionallity provided by Bucket4j. 

I will follow the progress of issue #410.

It's so kind of you and thank you very much.
