### ISSUE TITLE
Wrong assignment of JedisBasedProxyManager in documentation

### ISSUE THREAD

**Issue by aldobongio** [bucket4j/bucket4j#409]
The following line in the documentation is wrong

https://github.com/bucket4j/bucket4j/blob/cb43bfb538f494ff8df5ad0174f4001c0e7729c9/asciidoc/src/main/docs/asciidoc/distributed/redis/redis.adoc?plain=1#L69

The variable `proxyManager` must be of type `JedisBasedProxyManager`

**Comment by vladimir-bukhtoyarov** [comment]
will bereleased later
