### ISSUE TITLE
Maven Central Release 8.5

### ISSUE THREAD

**Issue by jimhcvent** [bucket4j/bucket4j#412]
Hi,

Thanks for what looks to be a really useful library!   Maven Central looks like it only has 7.6 right now, looking forward to being able to get hold of 8.5!

**Comment by vladimir-bukhtoyarov** [comment]
Hello @jimhcvent 

Pay attention that [goupId has changed](https://github.com/bucket4j/bucket4j/releases/tag/8.0.1) since ```8.0.0```
Use artifact that mentioneed in Readme https://github.com/bucket4j/bucket4j#get-dependency
