### ISSUE TITLE
Bucket4j with Redisson , the number of tokens is always same in bucket

### ISSUE THREAD

**Issue by amrit9326** [bucket4j/bucket4j#416]
I'm using these two dependency the code is also shared below , the issue is when I'm trying to run the application for the rate limit everytime I'm consuming the bucket its token is always the same. The expectation is suppose if the refill is set to 2mins and then if I'm consuming for the first time the left token should be 3 , then 2 then 1 and then 429 request.

<bucket4j.starter.version>0.9.1</bucket4j.starter.version><redisson.version>3.24.1</redisson.version>
<dependency>
    <artifactId>redisson-spring-boot-starter</artifactId>
    <exclusions>
        <exclusion>
            <artifactId>snakeyaml</artifactId>
            <groupId>org.yaml</groupId>
        </exclusion>
    </exclusions>
    <groupId>org.redisson</groupId>
    <version>${redisson.version}</version>
</dependency>
<dependency>
    <artifactId>bucket4j-spring-boot-starter</artifactId>
    <groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
    <version>${bucket4j.starter.version}</version>
</dependency>
@Configuration
public class RedisConfig {

    @Autowired
    private VcapUtils vcapUtils;

    @Bean
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer().setAddress(vcapUtils.getRedisURI());
        config.setCodec(new SerializationCodec());
        return Redisson.create(config);
    }

    @Bean
    public Config config() {
        Config config = new Config();
        config.useSingleServer().setAddress(vcapUtils.getRedisURI());
        config.setCodec(new SerializationCodec());
        return config;
    }

    @Bean(name = "springCM")
    public CacheManager cacheManager(Config config) {
        CacheManager cacheManager = Caching.getCachingProvider().getCacheManager();
        cacheManager.createCache("rateLimit", RedissonConfiguration.fromConfig(config));
        return cacheManager;
    }

    @Bean
    public ProxyManager<String> proxyManager(CacheManager cacheManager) {
        return new JCacheProxyManager<>(cacheManager.getCache("rateLimit"));
    }
}

@Component
public class RateLimitConfig extends OncePerRequestFilter {

    private static final Set<String> URL_TO_BE_IGNORED = Sets.newHashSet(
        "/dvh/api/v1/vehicle/$count",
        "/dvh/api/v1/vehicle/search",
        "/dvh/api/v1/vehicle/attributes"
    );

    @Autowired
    private BucketConfig bucketConfig;

    @Autowired
    private ProxyManager<String> proxyManager;

    private VcapApplication vcapApplication;

    @Autowired
    public RateLimitConfig() {
        this.vcapApplication = VcapApplication.fromEnvironment();
    }

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response,
        FilterChain filterChain) throws ServletException, IOException {

        Boolean requestURL = URL_TO_BE_IGNORED.contains(request.getRequestURI());

        if (Boolean.TRUE.equals(requestURL)) {
            filterChain.doFilter(request, response);
            return;
        }

        Bucket bucket = bucketConfig.resolveBucket(SpringSecurityContext.getToken().getZoneId());
        ConsumptionProbe probe = bucket.tryConsumeAndReturnRemaining(1);

        if (probe.isConsumed()) {
            response.setHeader("X-Rate-Limit-Remaining",
                String.valueOf(probe.getRemainingTokens()));
            filterChain.doFilter(request, response);
        } else {
            response.setHeader("X-Rate-Limit-Retry-After-Seconds",
                String.valueOf(probe.getNanosToWaitForRefill() / 1_000_000_000));
            response.setContentType(MediaType.APPLICATION_JSON_VALUE);
            response.setStatus(HttpStatus.TOO_MANY_REQUESTS.value());
        }
    }
}

@Component
public class BucketConfig {

    private static final Logger logger = LoggerFactory.getLogger(BucketConfig.class);

    private static final Integer DEFAULT_API_RATE_LIMIT = 4;

    private static final Integer REFILL_INTERVAL_IN_SECONDS = 2;

    @Autowired
    private ProxyManager<String> proxyManager;

    public Bucket resolveBucket(String tenantID) {
        Supplier<BucketConfiguration> configSupplier = getConfigSupplierForTenant(tenantID);
        return proxyManager.builder().build(tenantID, configSupplier);
    }

    private Supplier<BucketConfiguration> getConfigSupplierForTenant(String tenantID) {
        Bandwidth limit = Bandwidth.simple(DEFAULT_API_RATE_LIMIT,
            Duration.ofMinutes(REFILL_INTERVAL_IN_SECONDS)).withId(tenantID);
        return () -> (BucketConfiguration.builder()
            .addLimit(limit)
            .build());
    }
}
please Note I tried almost everything to make this code work but it didn't , the url and everything is fine and I don't want to go other way like hazelcast or jedis

**Comment by vladimir-bukhtoyarov** [comment]
First of all, you need to check that your cache satisfies Bucket4j requirements. You need to verify that  instance of `javax.cache.Cache` that you build as ```javacacheManager.getCache("rateLimit")``` invokes entry processors in isolation.  You should use `CompatibilityTest` by this link https://bucket4j.com/8.5.0/toc.html#verification-of-compatibility-with-a-particular-jcache-provider-is-your-responsibility

> I don't want to go other way like hazelcast or jedis

I do not think that you will achieve success with JCache over Redis, I have never seen any implementation that invokes entry-processors in isolation, like it invoked by idiomatic JCache implementations like Coherence, Ignite, Infinispan, Hazelcast. You already have Redisson in your classpath, so I do not see reasons why do not use direct integration for Redisson https://bucket4j.com/8.5.0/toc.html#example-of-bucket-instantiation-via-redissonbasedproxymanager

**Comment by amrit9326** [comment]
I'm using Java 17 , would this work https://bucket4j.com/8.5.0/toc.html#example-of-bucket-instantiation-via-redissonbasedproxymanager ? I don't think so. Also why jcache isn't working , internally when the spring starts @Bean(name = "springCM")
public CacheManager cacheManager(Config config) {
    CacheManager cacheManager = Caching.getCachingProvider().getCacheManager();
    cacheManager.createCache("rateLimit", RedissonConfiguration.fromConfig(config));
    return cacheManager;
}
its making the connection with redis , then why don't bucket4j is being saved through the cachemanager ,I checked a lot of post on medium and even github which suggested the same way I've done

**Comment by vladimir-bukhtoyarov** [comment]
> I'm using Java 17 , would this work https://bucket4j.com/8.5.0/toc.html#example-of-bucket-instantiation-via-redissonbasedproxymanager?

I do not know reasons, why it should not work with Java 17.

>  Also why jcache isn't working

The answer already provided in the previous post. Have you ran the `CompatibilityTest`?

**Comment by vladimir-bukhtoyarov** [comment]
@amrit9326 

Also, pay attention that you use third-party project https://github.com/MarcGiffing/bucket4j-spring-boot-starter that is addressed to provide zero-code solution. And in same time you manage buckets directly. It needs to choose concrete way. 

If your prefer zero code, that you need to address your questions there https://github.com/MarcGiffing/bucket4j-spring-boot-starter/discussions

If you want to manage buckets by yourself you should remove bucket4j-spring-boot-starter from classpath and add directly dependency to bucket4j jars.

**Comment by amrit9326** [comment]
Hi Vladimir 

I get below error when I try to add dependency for RedisProxyManager -
![image](https://github.com/bucket4j/bucket4j/assets/38880261/95f07f44-aac8-4302-9ea1-fd73ab3080a8)


I need to use some business logic in my case so I can't go with zero code.
I followed this repo and other articles where its was favored this way , so I followed 
https://github.com/kuldeepsingh99/api-rate-limiting

Could you please guide a way or suggest any example to do this successfully.
also I couldnt run test cause I can't connect to redis instance running on BTP Cloud from local , I've to deploy every time 
also can you suggest in constructor do I need to pass the cache created by cacheManager  public CompatibilityTest() throws InterruptedException {
    this.cache = cacheManager.getCache("rateLimit");
    this.test();
  }

**Comment by amrit9326** [comment]
My requirement is simple : I want to implement ratelimt using redis where the ratelimt would be on tenant based and there can be multiple instances of the same service, so ratelimt data must be shared which is why I'm using redis

**Comment by vladimir-bukhtoyarov** [comment]
> I get below error when I try to add dependency 

Dependency is deployed to Maven Central https://repo.maven.apache.org/maven2/com/bucket4j/bucket4j-redis/8.5.0/  
You have a problem with your maven repository proxy. Meat directly with admins who manage `int.repositories.cloud`.

> My requirement is simple : I want to implement ratelimt using redis where the ratelimt would be on tenant based and there can be multiple instances of the same service, so ratelimt data must be shared which is why I'm using redis

As I mentionned above, there is tests https://github.com/bucket4j/bucket4j/tree/8.5/bucket4j-redis/src/test/java/io/github/bucket4j/redis/redisson/cas that show how to instantiate `RedissonBasedProxyManager` , [for example](https://github.com/bucket4j/bucket4j/blob/8.5/bucket4j-redis/src/test/java/io/github/bucket4j/redis/redisson/cas/RedissonBasedProxyManagerFixedTtlTest.java#L66). You ask questions but do not read the answers.

**Comment by amrit9326** [comment]
Thanks a lot Vladimir but it would take time to get it added by the central team , could you suggest other way ?

**Comment by vladimir-bukhtoyarov** [comment]
> it would take time to get it added by the central team , could you suggest other way ?

Download dependency manually from Maven Central and put and commit it directly to your source code repository, then work with it on `system` scope:
```xml
 <dependency>
            <groupId>com.bucket4j</groupId>
            <artifactId>bucket4j-redis</artifactId>
            <version>8.5.0</version>
            <scope>system</scope>
            <!-- Point directly to jar from repository, because of temporary problems with dependency resolution
            <systemPath>${project.basedir}/lib/bucket4j-redis.jar</systemPath>
</dependency>
```

Also, you can [install dependency to local repository](https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html), but this way will work only on your local machine and builds will be failed on builders.

**Comment by amrit9326** [comment]
Hi Vladimir ,

As you suggested , I got it availed the above dependency in our central team.
Below is my code :

The first Time when I made the request -

![image](https://github.com/bucket4j/bucket4j/assets/38880261/15ab07a9-a9fd-43a2-a1b9-d4fdd5e1e16b)

The second time -
![image](https://github.com/bucket4j/bucket4j/assets/38880261/51c870e5-a47d-41b6-815b-20afbd711a26)

3rd Time
![image](https://github.com/bucket4j/bucket4j/assets/38880261/df44ba9b-b9fb-4511-8420-9e2db70b69a3)

4th Time
![image](https://github.com/bucket4j/bucket4j/assets/38880261/4117fd54-ff00-4441-93da-76cd44e45179)

5th Time
![image](https://github.com/bucket4j/bucket4j/assets/38880261/01b58a87-1015-45da-a5ae-366d996a42d9)

The behaviour is very different , each time the x-rate-limit-remaining is different , suppose I'm making request at first time and the api is taking on average 2s , so the next time again remaining rate limit should come 3 again but its coming 2 then 1 then 0 and again then its being refilled with just one token, the tokens are being refilled randomly , sharing my code :


@Component
public class BucketConfig {

  private static final long DEFAULT_API_RATE_LIMIT = 4;

  private static final long REFILL_INTERVAL_IN_SECONDS = 1;

  @Autowired
  private ProxyManager<String> proxyManager;


  public Bucket resolveBucket(String tenantID) {
    Supplier<BucketConfiguration> configSupplier = this.getConfigSupplierForUser(tenantID);
    return proxyManager.builder().build(tenantID, configSupplier);
  }

  private Supplier<BucketConfiguration> getConfigSupplierForUser(String tenantID) {
    Bandwidth limit = Bandwidth.simple(DEFAULT_API_RATE_LIMIT,
        Duration.ofSeconds(REFILL_INTERVAL_IN_SECONDS)).withId(tenantID);
    return () -> (BucketConfiguration.builder()
        .addLimit(limit).build());
  }
}


@Component
public class RateLimitConfig implements Filter {

  private static final Set<String> URL_TO_BE_IGNORED = Sets.newHashSet("/dvh/api/v1/vehicle/$count",
      "/dvh/api/v1/vehicle/search", "/dvh/api/v1/vehicle/attributes");
  @Autowired
  private BucketConfig bucketConfig;
  private VcapApplication vcapApplication;

  @Autowired
  public RateLimitConfig() {
    this.vcapApplication = VcapApplication.fromEnvironment();
  }

  @Override
  public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse,
      FilterChain filterChain) throws IOException, ServletException {

    HttpServletRequest httpServletRequest = (HttpServletRequest) servletRequest;
    HttpServletResponse httpServletResponse = (HttpServletResponse) servletResponse;

    Boolean requestURL = URL_TO_BE_IGNORED.contains(httpServletRequest.getRequestURI());

    if (Boolean.TRUE.equals(requestURL)) {
      filterChain.doFilter(servletRequest, servletResponse);
      return;
    }

    Bucket bucket = bucketConfig.resolveBucket(SpringSecurityContext.getToken().getZoneId());
    ConsumptionProbe probe = bucket.tryConsumeAndReturnRemaining(1);

    String vcapInstanceId = vcapApplication.getInstanceId();
    if (probe.isConsumed()) {
      httpServletResponse.setHeader("X-Rate-Limit-Remaining",
          String.valueOf(probe.getRemainingTokens()));
      httpServletResponse.setHeader("instance_id",
          vcapInstanceId);
      filterChain.doFilter(servletRequest, servletResponse);
    } else {
      httpServletResponse.setHeader("X-Rate-Limit-Retry-After-Seconds",
          String.valueOf(probe.getNanosToWaitForRefill() / 1_000_000_000));
      httpServletResponse.setHeader("instance_id",
          vcapInstanceId);
      httpServletResponse.setContentType(MediaType.APPLICATION_JSON_VALUE);
      httpServletResponse.setStatus(HttpStatus.TOO_MANY_REQUESTS.value());
    }
  }
}

@Configuration
public class RedisConfig {

  @Autowired
  private VcapUtils vcapUtils;


  @Bean
  public ConnectionManager createRedissonClient() {
    Config config = new Config();
    config.useSingleServer().setAddress(vcapUtils.getRedisURI());
    return ConfigSupport.createConnectionManager(config);
  }

  @Bean
  public CommandAsyncExecutor createRedissonExecutor(ConnectionManager connectionManager) {
    return new CommandAsyncService(connectionManager, null,
        RedissonObjectBuilder.ReferenceType.DEFAULT);
  }


  @Bean
  public ProxyManager<String> getProxyManager(CommandAsyncExecutor commandExecutor) {
    return RedissonBasedProxyManager.builderFor(commandExecutor)
        .withExpirationStrategy(ExpirationAfterWriteStrategy.none())
        .build();
  }
}

**Comment by amrit9326** [comment]
Thanks Vladimir , the RedisproxyManager works fine on multiple instances.
