### ISSUE TITLE
Question: Bucket4J Release 8.6 on Maven-Central

### ISSUE THREAD

**Issue by kindlich** [bucket4j/bucket4j#418]
Hey there,

I just saw that on MavenCentral Bucket4J is already on version [8.6](https://central.sonatype.com/artifact/com.bucket4j/bucket4j-core/8.6.0), whereas the main branch and the latest release here on GitHub are on 8.5.

Is the 8.6 version already "stable" or was it published accidentally?

**Comment by vladimir-bukhtoyarov** [comment]
@kindlich yes it is stable. Just have no time to complete release releated activities, I am going to finish it on weekend. There is only one issue in the scope https://github.com/bucket4j/bucket4j/issues/417

**Comment by vladimir-bukhtoyarov** [comment]
release artifacts have been created
