### ISSUE TITLE
Inconsistency in Table Naming for JDBC Integrations in Bucket4j Documentation

### ISSUE THREAD

**Issue by dkswnkk** [bucket4j/bucket4j#434]
In the source code, specifically at [this link](https://github.com/bucket4j/bucket4j/blob/master/bucket4j-core/src/main/java/io/github/bucket4j/distributed/jdbc/BucketTableSettings.java#L57), the table name is set to bucket.

However, in the official documentation under [JDBC integrations](https://bucket4j.com/8.7.0/toc.html#jdbc-integrations), the recommended table name is buckets.

I think having consistency in documentation and code will reduce confusion, what do you think?

**Comment by vladimir-bukhtoyarov** [comment]
Docs havr been fixed and will be updated with next release.
