### ISSUE TITLE
Client-side config is ignored since 8.9.0

### ISSUE THREAD

**Issue by galexeyev** [bucket4j/bucket4j#464]
Hello @vladimir-bukhtoyarov,
First of all, as this is my first issue here, thank you for such a great library and for all your efforts!

I see that in bucket4j version >= 8.9.0, the new constructor in `PostgreSQLadvisoryLockBasedProxyManager` is ignoring `ClientSideConfig` that was previously expected from `SQLProxyConfiguration`. 

Is it an intended change? If yes, then maybe the changes should also be reflected in the documentation examples?

Examples in the documentation: https://bucket4j.com/8.9.0/toc.html#postgresql-integration

Changed part: https://github.com/bucket4j/bucket4j/compare/8.8.0...8.10.0#diff-84bb27f35550de154b5b7a79fe04fed12eba7675fa240fa4e48d9de97e362663R66

Thank you in advance!

**Comment by vladimir-bukhtoyarov** [comment]
Hello @galexeyev 

I forgot that cfg can be passed in this way. I will update docomentation.

**Comment by galexeyev** [comment]
Thank you!

**Comment by vladimir-bukhtoyarov** [comment]
>  I will update docomentation.

After rethinking, I have decided to fix original problem. Broken constructors have been fixed. Fix is available in version 8.10.1
