### ISSUE TITLE
Publish relocation info to Maven-central

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [bucket4j/bucket4j#470]
It looks that many projects is not aware about groupId change that happen at `8.0.0` version when `com.github.vladimir-bukhtoyarov` was changed to `com.bucket4j`, there are [many fresh](https://mvnrepository.com/artifact/com.github.vladimir-bukhtoyarov/bucket4j-core/usages?sort=newest) releases continue to use legacy groupId.

So it needs to notify users via [Maven Central Relocation Mechanism](https://maven.apache.org/guides/mini/guide-relocation.html) that groupId was changed.

**Comment by pavera** [comment]
@vladimir-bukhtoyarov It seems [from the docs](https://maven.apache.org/guides/mini/guide-relocation.html#releasing-the-next-version) that an actual 7.6.1 should have been published to the new group id to allow maven to resolve the relocation automatically? Currently I'm seeing CI failures because Dependabot attempted to bump a pom.xml to 7.6.1, but maven can't find that release in `com.bucket4j`

**Comment by vladimir-bukhtoyarov** [comment]
I will release a fix tomorrow.

**Comment by vladimir-bukhtoyarov** [comment]
Old groupId has been released with version 8.0.1 and relocation info. New gouupId has been release with version 7.6.1.

I suppose that it is enough to fix relocation relationship. Some CI can be still failed if not prepared that bytrcode changed to java 11, but seamless migration of groupId was not a goal, intent of #470 is signaling to users that they use groupId that is not maintained anymore.

**Comment by MrVelotro1** [comment]
@vladimir-bukhtoyarov I see this on maven and can use it no problem, but the code is missing from this repo (release 7.6.1), was this tag deleted?

**Comment by vladimir-bukhtoyarov** [comment]
Hello @MrVelotro1

There is no tag for 7.6.1

**Comment by MrVelotro1** [comment]
I see, 

Other than the sparse class name changes (eg. Bucket4j.configurationBuilder() to BucketConfiguration.builder()), 
is 8.0.x (or 8.x.x) backwards compatible with 7.6.0?

**Comment by vladimir-bukhtoyarov** [comment]
The intent of 8.0.0 was changing to person-neutral groupId, from com.github.vladimir-bukhtoyarov to com.bucket4j.

There are no another changes.
