### ISSUE TITLE
Migrate to JDK 17

### ISSUE THREAD

**Issue by vladimir-bukhtoyarov** [bucket4j/bucket4j#474]
Requirements:
* Builds for Java 11 should be provided in same way as it currently implemented for Java 8 - via dedicated artifact name.
* Change artifact naming scheme. Targed JDK version should be a part of maven artifact name. For example `bucket4_jdk17-core`, `bucket4_jdk11-core`. This will allow to avoid breaking the builds for clients who had set up auto-fetch newest dependencies. As well as reduce amount of questions related to bytecode version of compiled artifacts.

**Comment by filiphr** [comment]
We are in the process of upgrading our dependencies and I noticed that the artifact ids changed. We are using this as a library and our users can then use an upgraded version if they want to. 

I don't fully understand the reason with using `_jdkxx-core` in the artifact-id. Why don't you use multi release JARs and have a single artifact id. If some dependencies require java 17 then those artifacts will be compiled with source and target 17, the rest will be 11. If you document this well it should be clear for users. If you want to change your baseline then you can upgrade the major version. e.g. to go to baseline 21 you can use version 9.x.

This would make it easy to follow and easy to upgrade as it would only require people to change the version. Additionally, it would also make it possible for 2 different libraries to use bucket4j, one would be using an older version and the other one a newer one. With Maven / Gradle it can easily be that the correct version is then used, when using different artifact ids then there will be a clash on the runtime.

**Comment by vladimir-bukhtoyarov** [comment]
Multi release Jars requires to keep open code base for previos JDK versions, so it makes impossible to get monetixation for paid distributions like this https://bucket4j.com/commercial/java8.html

**Comment by filiphr** [comment]
That is completely understandable. What I would suggest then is to keep the open source bits for the version of Java that is free without any change in the artifact id.

For the paid commercial support you can do it using a different group id.

For example have a look at how jOOQ does his. https://www.jooq.org/doc/3.19/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step1/

**Comment by vladimir-bukhtoyarov** [comment]
There is no big differences beetwen dedicated groub-id and dedicated artifact-id for paid artifact, I think this point can be left out of current discussion, the same as multi-release jars.

Motivation to add suffix for latest artifact-id is descibed in first message of this issue. I will think about your question again at September 2025, when Java 25 will be available.

**Comment by filiphr** [comment]
My main point was the fact that having multiple maven central artifacts that contain the same code can easily lead to having issues with split packages.

I don't fully understand the reasoning for having the JDK in the artifact for the Open Source artifacts. If someone wants to use a specific version they could do that. What I am basically asking for is to have artifacts without the JDK specifics, then everyone can decide on their own what they want to use for this.
