### ISSUE TITLE
Factory method 'proxyManagerLocal' threw exception with message: Expiration-after-write is not supported

### ISSUE THREAD

**Issue by ddrzymala** [bucket4j/bucket4j#480]
Hi,

Latest version 8.11.0
I was trying to replace deprecated method but I'm getting "Expiration-after-write is not supported" excpetion.
I use Lettuce client:

 @Bean
    LettuceBasedProxyManager<String> proxyManagerLocal(RedisClient redisClient) {

        StatefulRedisConnection<String, byte[]> redisConnection = redisClient
                .connect(RedisCodec.of(StringCodec.UTF8, ByteArrayCodec.INSTANCE));

        return Bucket4jLettuce.casBasedBuilder(redisConnection)
                .expirationAfterWrite(ExpirationAfterWriteStrategy.basedOnTimeForRefillingBucketUpToMax(Duration.ofSeconds(10)))
                .build();
    }

Is this is expected and that ProxyManger does not support TTL? If this is the case how one should setup TTL?
In the docs clear shows that this can be used:
https://bucket4j.com/8.11.0/toc.html#example-of-bucket-instantiation-via-lettucebasedproxymanager

Cheers

**Comment by ddrzymala** [comment]
Yes this is what I did. Thanks.

**Comment by vladimir-bukhtoyarov** [comment]
Fix has been released with version `8.11.1`
