### ISSUE TITLE
lockBasedBuilder and expirationAfterWrite

### ISSUE THREAD

**Issue by exposed2s** [bucket4j/bucket4j#504]
Hello, while trying to build a HazelcastLockBasedProxyManager I stumbled upon what I think is a bug,

if I use

`HazelcastLockBasedProxyManager<String> proxyManager = Bucket4jHazelcast.lockBasedBuilder(map).expirationAfterWrite(expiration).build();`

I'll get a UnsupportedOperationException with the message "Expiration-after-write is not supported"

but If I use the deprecated constructor, it works as expected.
`ClientSideConfig config = ClientSideConfig.getDefault().withExpirationAfterWriteStrategy(expiration);`
        `proxyManager = new HazelcastLockBasedProxyManager<>(map, config);`

I'm using bucket4j_jdk11-hazelcast 8.13.1

**Comment by exposed2s** [comment]
Sounds good! Thank you.

**Comment by vladimir-bukhtoyarov** [comment]
Will be released soon in the scope of `8.14.0`
