### ISSUE TITLE
Missing tag for bucket4j-coherence version 7.6.1

### ISSUE THREAD

**Issue by SeePatPlay** [bucket4j/bucket4j#508]
Hi, 
I'm using the version  buket4j-coherence 7.6.1 however I do not see a tag/branch associated with this version.

https://mvnrepository.com/artifact/com.bucket4j/bucket4j-coherence/7.6.1

**Comment by vladimir-bukhtoyarov** [comment]
There is no tag for this version, because 7.6.1 artifacts are eddressed to be just a marker that  groupId of artifact was changed

![image](https://github.com/user-attachments/assets/2206a94c-dd46-4d21-bfc6-8f19d05c8040)

**Comment by SeePatPlay** [comment]
Thank you for your response
Is there anyway to find the SHA that corresponds to this code? Would it be 7.6.0?

**Comment by vladimir-bukhtoyarov** [comment]
There is no published commit. Just stay at 7.6.0 if you do not want to upgrade to new groupId.
