### ISSUE TITLE
Documentation issue different JDK artifacts

### ISSUE THREAD

**Issue by wsalembi** [bucket4j/bucket4j#509]
The documentation site (https://bucket4j.com/8.13.1/toc.html) is not yet up to date with the new JDK artifacts. It links to the the java compatibility matrix (https://github.com/bucket4j/bucket4j/tree/8.0#java-compatibility-matrix) that doesn't document the new libs yet.

**Comment by vladimir-bukhtoyarov** [comment]
@wsalembi attach screenshot please

**Comment by vladimir-bukhtoyarov** [comment]
I have catch it, will fix soon

**Comment by vladimir-bukhtoyarov** [comment]
Instructions to get Java 8 builds has been fized
