### ISSUE TITLE
No longer an easy way to configure Caffeine with a keepAfterRefillDuration

### ISSUE THREAD

**Issue by PascalSchumacher** [bucket4j/bucket4j#512]
`CaffeineProxyManager(Caffeine<? super K, ? super RemoteBucketState> builder, Duration keepAfterRefillDuration)` is now deprecated, but I do not see an easy way to configure it using `Bucket4jCaffeine#builderFor(Caffeine)`. The only way seems to be implementing a custom `Expiry`.

Maybe the Bucket4jCaffeine builder can be extended to make this easy again, or am I missing something?

By the way: Thank you very much for providing bucket4j

**Comment by vladimir-bukhtoyarov** [comment]
Hello @PascalSchumacher

> am I missing something

Yes. In latest version more flexible way was added:

```java
CaffeineProxyManager<Long> cacheManager = Bucket4jCaffeine
            .<Long>builderFor(Caffeine.newBuilder().maximumSize(100))
            .expirationAfterWrite(ExpirationAfterWriteStrategy.basedOnTimeForRefillingBucketUpToMax(Duration.ofSeconds(10))) // as it was previously
//            .expirationAfterWrite(ExpirationAfterWriteStrategy.fixedTimeToLive(Duration.ofSeconds(120))) or like this
//            .expirationAfterWrite(ExpirationAfterWriteStrategy.none()) or even like this
            .build();
```

I will add documentation for Caffine later.

**Comment by PascalSchumacher** [comment]
Thank you very much!
