### ISSUE TITLE
Issue with Infinispan Hotrod client

### ISSUE THREAD

**Issue by crey93** [bucket4j/bucket4j#521]
Hello there!.

I'm facing an error when i try to integrate bucket4j with an infinispan hotrod client. 

I followed the steps like the test:
https://github.com/bucket4j/bucket4j/blob/master/bucket4j-infinispan-all/bucket4j-infinispan/src/test/java/io/github/bucket4j/grid/infinispan/InfinispanHotrodTest.java

But when finally i use this for a real Infinispan Server (v12.0.0)

I receive the following error:
`java.lang.IllegalArgumentException: ISPN027002: Unknown task 'bucket4j_readWriteMapBased_task'`

Any advice will help. Thanks

**Comment by vladimir-bukhtoyarov** [comment]
Bucket4j provides all required metadata via https://github.com/bucket4j/bucket4j/blob/master/bucket4j-infinispan-all/bucket4j-infinispan/src/main/resources/META-INF/services/org.infinispan.tasks.ServerTask it should be no special configuration, just add following jars to classpath of Hotrod server:
```xml
<dependency>
  <groupId>com.bucket4j</groupId>
  <artifactId>bucket4j_jdk17-core</artifactId>
  <version>8.14.0</version>
</dependency>
<dependency>
  <groupId>com.bucket4j</groupId>
  <artifactId>bucket4j_jdk17-infinispan</artifactId>
  <version>8.14.0</version>
</dependency>
```
